---
title: "MATH 110D. Mathematical Analysis"
format: 
  html:
    toc: true
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

[Office Hours Update](office_hours.html)

| Week | Date | Section/Topic | Lecture | Assignments |
|:---:|:---|:---|:---|:---|
| 1 | 1/21 | Linear Functions | [Note](notes_d/Linear/Linear_Functions.pdf) | |
| 2 | 1/28 | Applications of Linear Functions | [Pre - Notes](notes_d/Linear/Applications of Linear Functions.pdf),  [Notes](notes_d/Linear/post_applications.pdf) | |
| 3 | 2/4 | Review for Exam 1  | [Practice 1](exams/exam1_practice1.pdf), [Solution](exams/exam1_practice1_sol.pdf) <br> [Practice 2](exams/exam1_practice2.pdf), [Solution](exams/exam1_practice2_sol.pdf) | |
| 3 | 2/4 |  <u>**Exam 1**</u>  | [Exam 1's Solution](exams/exam1_sol.pdf) | |
| 4 | 2/11 | Quadratic Functions | [Note](notes_d/Quadratic/Solving_Graphing.pdf) | [Assignment 1](assignments/a1.html) |
| 5 | 2/18 | Applications of Quadratic Functions | [Notes](notes_d/Quadratic/QuadraticsApplications.pdf) | |
| 6 | 2/25 | Exponential Functions | [Note](notes_d/Exponential/Exponential%20Functions.pdf) | |
| 7 | 3/4 | Review for Exam 2  | [Practice 1](exams/exam2_practice1.pdf), [Solution](exams/exam2_practice1_sol.pdf) <br> [Practice 2](exams/exam2_practice2.pdf), [Solution](exams/exam2_practice2_sol.pdf) <br> [Practice 3](exams/exam2_practice3.pdf), [Solution](exams/exam2_practice3_sol.pdf) | |
| 7 | 3/4 |  <u>**Exam 2**</u> | [Solution](exams/exam2_solution.pdf) | |
| 8 | 3/11 | Applications of Exponential Functions | [Notes 1](notes_d/Exponential/ExponentialApplications1.pdf), [Notes 2](notes_d/Exponential/ExponentialApplications2.pdf) | |
| 9 | 3/18 | **Spring Break** | | |
|  |  | [Exam 3's Practice and Solution](exams/exam3_practice1_solution.pdf) <br>  [<u>**Exam 3**</u>](exams/exam3.pdf) (Take Home - Due 3/30)   | | |
| 10 | 3/25 | Derivatives  | [Notes](notes_d/Derivatives/Doc1.pdf) | |
| 11 | 4/1 | Applications of Derivatives | [Notes](notes_d/Derivatives/ApplicationsofDerivatives.pdf) | |
| 12 | 4/8 | **Reday - No Classes** | | |
| 13 | 4/15 | Review for Exam 4  | [Practice 1](exams/exam4_practice1.pdf), [Solution](exams/exam4_practice1_sol.pdf) <br> [Practice 2](exams/exam4_practice2.pdf), [Solution](exams/exam4_practice2_sol.pdf)<br> [Practice 3](exams/exam4_practice3.pdf), [Solution](exams/exam4_practice3_sol.pdf) | |
| 13 | 3/4 |  <u>**Exam 4**</u> | [Solution](exams/exam4_sol.pdf) | |
| 14 | 4/22 | Linear Programming and Applications | [Notes](notes_d/LP/LinearProgramming3.pdf) | [Assignment 2](assignments/a2.html) |
| 15 | 4/29 | Review for Final | | |
| 16 | 5/6 | <u>**Final Exam**</u> (8:30 am - 11:00 am)  | [Practice 1](exams/exam5_practice1.pdf), [Solution](exams/exam5_practice1_sol.pdf) <br> [Practice 2](exams/exam5_practice2.pdf), [Solution](exams/exam5_practice2_sol.pdf)<br> [Practice 3](exams/exam5_practice3.pdf), [Solution](exams/exam5_practice3_sol.pdf) | |
: {.striped .hover}

