---
title: "Math 122: Exam 1 - Practice"
format:
  pdf:
    documentclass: article
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
    header-includes: |
      \usepackage{amsmath,amssymb,amsthm}
      \usepackage{enumitem}
      \usepackage{fancyhdr}
      \pagestyle{fancy}
      \fancyhf{}
      \lhead{\textbf{Math 101: Final Exam}}
      \rhead{\textbf{Fall 2026}}
      \cfoot{\thepage}
  html:
    toc: false
    theme: cosmo
---
**Instructions:**

- Show all work: Full credit requires complete, correct steps and proper math notation.

- Points: Each question is worth 10 points.

- Formula Sheet: Permitted (formulas only; no worked examples).

- Calculators: Basic, non-graphing calculators allowed.

---

# Practice 1

### Problem 1 (Section 5.4)
Find the exact arc length of the curve 
$$ y = 3x^{3/2} - 1 $$ 
over the interval from $x = 0$ to $x = 1$.

\vspace{3cm}

### Problem 2 (Section 6.5)
Find the limit:
$$ \lim_{x \to 0} \frac{e^x - 1}{\sin x} $$

\vspace{3cm}


### Problem 3 (Section 6.5)
Find the limit:
$$ \lim_{x \to +\infty} x e^{-x} $$

\vspace{3cm}


### Problem 4 (Section 6.5)
Find the limit:
$$ \lim_{x \to 0} \left(e^x + x\right)^{1/x} $$

\vspace{3cm}

### Problem 5 (Section 6.7)
Find $\frac{dy}{dx}$:
$$ y = \sin^{-1}(1/x) $$

\vspace{3cm}

### Problem 6 (Section 6.7)
Find $\frac{dy}{dx}$:
$$ y = e^x \sec^{-1} x $$

\vspace{3cm}

### Problem 7 (Section 6.7)
Evaluate the integral:
$$ \int \frac{dx}{\sqrt{1 - 4x^2}} $$

\vspace{3cm}

### Problem 8 (Section 6.7)
Evaluate the integral:
$$ \int \frac{\sec^2 x \, dx}{\sqrt{1 - \tan^2 x}} $$

\vspace{3cm}

### Problem 9 (Section 6.7)
Evaluate the definite integral:
$$ \int_{1}^{\sqrt{3}} \frac{\sqrt{\tan^{-1}x}}{1 + x^2} \, dx $$

\vspace{3cm}

### Problem 10 (Section 6.7)
Evaluate the integral:
$$ \int \frac{\sin\theta}{\cos^2\theta + 1} \, d\theta $$

\vspace{3cm}

---

# Practice 2


### Problem 1
Find the exact arc length of the curve over the interval from $x = 0$ to $x = 1$:
$$ y = (2x + 1)^{3/2} $$

\vspace{3cm}



### Problem 2
Find the limit:
$$ \lim_{x \to 0} \frac{\tan(2x)}{\ln(1 + x)} $$

\vspace{3cm}



### Problem 3
Find the limit:
$$ \lim_{x \to +\infty} x^2 e^{-2x} $$

\vspace{3cm}



### Problem 4
Find the limit:
$$ \lim_{x \to 0^+} (1 + 2x)^{1/x} $$

\vspace{3cm}



### Problem 5
Find $\frac{dy}{dx}$:
$$ y = \cos^{-1}\left(\frac{1}{x^2}\right) $$

\vspace{3cm}



### Problem 6
Find $\frac{dy}{dx}$:
$$ y = \sin^{-1}x \cdot \cos^{-1}(x) $$

\vspace{3cm}



### Problem 7
Evaluate the integral:
$$ \int \frac{dx}{{1 + 9x^2}} $$

\vspace{3cm}


### Problem 8
Evaluate the integral:
$$ \int \frac{ x \, dx}{\sqrt{1 - x^4}} $$

\vspace{3cm}



### Problem 9
Evaluate the definite integral:
$$ \int_{0}^{1} \frac{\left(\sin^{-1}x\right)^3}{\sqrt{1 - x^2}} \, dx $$

\vspace{3cm}



### Problem 10
Evaluate the integral:
$$ \int \frac{e^x}{1+e^{2x}} \, dx $$

\vspace{3cm}

\vfill